In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline

In [2]:
df=pd.read_csv('iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [5]:
df.isnull()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [6]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
data = df.values
X = data[:,:-1]
Y = data[:,-1]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [9]:
print(X_train)

[[24 5.1 3.3 1.7 0.5]
 [94 5.0 2.3 3.3 1.0]
 [3 4.7 3.2 1.3 0.2]
 [95 5.6 2.7 4.2 1.3]
 [76 6.6 3.0 4.4 1.4]
 [117 6.5 3.0 5.5 1.8]
 [41 5.0 3.5 1.3 0.3]
 [88 6.3 2.3 4.4 1.3]
 [132 7.9 3.8 6.4 2.0]
 [64 6.1 2.9 4.7 1.4]
 [59 6.6 2.9 4.6 1.3]
 [99 5.1 2.5 3.0 1.1]
 [10 4.9 3.1 1.5 0.1]
 [4 4.6 3.1 1.5 0.2]
 [143 5.8 2.7 5.1 1.9]
 [52 6.4 3.2 4.5 1.5]
 [127 6.2 2.8 4.8 1.8]
 [87 6.7 3.1 4.7 1.5]
 [36 5.0 3.2 1.2 0.2]
 [130 7.2 3.0 5.8 1.6]
 [73 6.3 2.5 4.9 1.5]
 [28 5.2 3.5 1.5 0.2]
 [137 6.3 3.4 5.6 2.4]
 [82 5.5 2.4 3.7 1.0]
 [74 6.1 2.8 4.7 1.2]
 [50 5.0 3.3 1.4 0.2]
 [19 5.7 3.8 1.7 0.3]
 [114 5.7 2.5 5.0 2.0]
 [142 6.9 3.1 5.1 2.3]
 [101 6.3 3.3 6.0 2.5]
 [47 5.1 3.8 1.6 0.2]
 [105 6.5 3.0 5.8 2.2]
 [30 4.7 3.2 1.6 0.2]
 [77 6.8 2.8 4.8 1.4]
 [26 5.0 3.0 1.6 0.2]
 [69 6.2 2.2 4.5 1.5]
 [138 6.4 3.1 5.5 1.8]
 [147 6.3 2.5 5.0 1.9]
 [83 5.8 2.7 3.9 1.2]
 [15 5.8 4.0 1.2 0.2]
 [102 5.8 2.7 5.1 1.9]
 [40 5.1 3.4 1.5 0.2]
 [1 5.1 3.5 1.4 0.2]
 [17 5.4 3.9 1.3 0.4]
 [38 4.9 3.1 1.5 0.1]


In [10]:
print(X_test)

[[131 7.4 2.8 6.1 1.9]
 [53 6.9 3.1 4.9 1.5]
 [97 5.7 2.9 4.2 1.3]
 [92 6.1 3.0 4.6 1.4]
 [84 6.0 2.7 5.1 1.6]
 [32 5.4 3.4 1.5 0.4]
 [12 4.8 3.4 1.6 0.2]
 [18 5.1 3.5 1.4 0.3]
 [103 7.1 3.0 5.9 2.1]
 [55 6.5 2.8 4.6 1.5]
 [124 6.3 2.7 4.9 1.8]
 [148 6.5 3.0 5.2 2.0]
 [57 6.3 3.3 4.7 1.6]
 [9 4.4 2.9 1.4 0.2]
 [89 5.6 3.0 4.1 1.3]
 [96 5.7 3.0 4.2 1.2]
 [79 6.0 2.9 4.5 1.5]
 [39 4.4 3.0 1.3 0.2]
 [93 5.8 2.6 4.0 1.2]
 [66 6.7 3.1 4.4 1.4]
 [51 7.0 3.2 4.7 1.4]
 [108 7.3 2.9 6.3 1.8]
 [70 5.6 2.5 3.9 1.1]
 [46 4.8 3.0 1.4 0.3]
 [56 5.7 2.8 4.5 1.3]
 [49 5.3 3.7 1.5 0.2]
 [7 4.6 3.4 1.4 0.3]
 [44 5.0 3.5 1.6 0.6]
 [123 7.7 2.8 6.7 2.0]
 [34 5.5 4.2 1.4 0.2]]


In [11]:
from sklearn.svm import SVC
svn = SVC()
svn.fit(X_train, y_train)

SVC()

In [12]:
predictions = svn.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

0.9666666666666667

In [13]:
from sklearn.linear_model import LogisticRegression

logistic_reg = LogisticRegression(solver='saga')
logistic_reg.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(solver='saga')

In [14]:
training_prediction = logistic_reg.predict(X_train)
training_prediction

array(['Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'I

In [15]:
test_prediction = logistic_reg.predict(X_test)
test_prediction

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa'],
      dtype=object)